// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// IdentificationRisk
Rcpp::List IdentificationRisk(Rcpp::NumericMatrix dataMatrix, int rows, int cols, Rcpp::List syndataMatrices, int num, NumericVector knowncols, int numKnown, NumericVector syncols, int numSyn);
RcppExport SEXP _categorical_IdentificationRisk(SEXP dataMatrixSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP syndataMatricesSEXP, SEXP numSEXP, SEXP knowncolsSEXP, SEXP numKnownSEXP, SEXP syncolsSEXP, SEXP numSynSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dataMatrix(dataMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type syndataMatrices(syndataMatricesSEXP);
    Rcpp::traits::input_parameter< int >::type num(numSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type knowncols(knowncolsSEXP);
    Rcpp::traits::input_parameter< int >::type numKnown(numKnownSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type syncols(syncolsSEXP);
    Rcpp::traits::input_parameter< int >::type numSyn(numSynSEXP);
    rcpp_result_gen = Rcpp::wrap(IdentificationRisk(dataMatrix, rows, cols, syndataMatrices, num, knowncols, numKnown, syncols, numSyn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_categorical_IdentificationRisk", (DL_FUNC) &_categorical_IdentificationRisk, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_categorical(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
