# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function will compute the identification risk for a dataset with synthetic categorical variables.
#' @param origdata dataframe of the origonal data
#' @param syndata list of the different synthetic dataframes
#' @param known vector of the names of the columns in the dataset assumed to be known
#' @param syn vector of the names of the columns in the dataset that are synthetic
#' @export
IdentificationRisk <- function(dataMatrix, rows, cols, syndataMatrices, num, knowncols, numKnown, syncols, numSyn) {
    .Call('_categorical_IdentificationRisk', PACKAGE = 'categorical', dataMatrix, rows, cols, syndataMatrices, num, knowncols, numKnown, syncols, numSyn)
}

