# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function will compute the identification risk for a dataset with synthetic categorical variables.
#' @param origdata dataframe of the origonal data
#' @param syndata list of the different synthetic dataframes
#' @param known vector of the names of the columns in the dataset assumed to be known
#' @param syn vector of the names of the columns in the dataset that are synthetic
.IdentificationRiskC <- function(dataMatrix, rows, cols, syndataMatrices, num, knowncols, numKnown, syncols, numSyn) {
    .Call('_IdentificationRiskCalculation_IdentificationRiskC', PACKAGE = 'IdentificationRiskCalculation', dataMatrix, rows, cols, syndataMatrices, num, knowncols, numKnown, syncols, numSyn)
}

#' This function will compute the identification risk for a dataset with synthetic continuous and categorical variables.
#' @param origdata dataframe of the origonal data
#' @param syndata list of the different synthetic dataframes
#' @param known vector of the names of the columns in the dataset assumed to be known
#' @param syn vector of the names of the columns in the dataset that are synthetic
#' @param radius radius to compare with for continous variables. Radius is either percentage (default) or fixed.
#' Radius can be the same for all continuous variables or specific to each. To specify for each use a vector, with
#' the radii ordered in the same order those columns appear in the dataset.
#' @param percentage true for a percentage radius, false for a constant radius
#' @param euclideanDist true for a euclidean distance radius, false otherwise
#' @param categoricalVector Boolean vector corresponding to the number of columns in the data, true means that column is categorical.
.IdentificationRiskContinuousC <- function(dataMatrix, rows, cols, syndataMatrices, num, knowncols, numKnown, syncols, numSyn, radius, percentage, euclideanDist, categoricalVector) {
    .Call('_IdentificationRiskCalculation_IdentificationRiskContinuousC', PACKAGE = 'IdentificationRiskCalculation', dataMatrix, rows, cols, syndataMatrices, num, knowncols, numKnown, syncols, numSyn, radius, percentage, euclideanDist, categoricalVector)
}

